### PR TITLE
Removed Nest + Nest Dependencies & Added Express w/ TS-Node

### PR DESCRIPTION
**Pull request by one2code**
**Fixes:** #53 

1. Removed all associated Nest files from `/src` folder and replaced them with index.ts
2. Uninstalled all Nest & Nest related dependencies including Jest from package.json with npm uninstall --save dev
3. Modified the tsconfig.json file, removing Nest related configurations
4. Updated the compiler configuration in tsconfig.json, changed the `"module:"` value from `"CommonJS"` to `"NodeNext"`
5. Added `"ModuleResolution:" "NodeNext"`
6. Removed `"type": "module"` from tsconfig.json
7. Added NPM package TS-Node for seamless Typescript compilation and developer workflow
8. Updated TypeScript compilation target to `"ES2020"` to allow for implementation of more recent JS syntax
9. Setup and tested Express Server on port 3000 in Index.ts

### CODE REVIEW

**Comment by one2code** [comment]
Going to add @DaleOrders to the review to take a look. I removed "build" from the tsconfig.json because I implemented the TS-Node package, so we do not have to manually compile the ts file every time we run index.ts. Unfortunately, this will fail the current implementation of the Node.js linter. I know I tested this live with @0916dhkim and the server runs properly with the ts file. @DaleOrders let me know your thoughts, and if you're ok with this, we can create a separate issue to update the linter to remove the "build" check.

**Comment by DaleOrders** [comment]
Yeah I think that sounds like a good approach. Happy for us to do that.

**Comment by one2code** [comment]
@0916dhkim @DaleOrders I saw the fix Dale put in for the frontend and created a separate issue for the backend. I'll do a draft PR for the backend check as well, and then we can coordinate our pull requests so we do not have any merge conflicts.

**Comment by one2code** [comment]
@0916dhkim I just realized something now before bed! We should add `--respawn --transpile-only` to scripts> start in package.json, so the server automatically restarts after every edit. Will help with testing/ developer experience. If you want to request changes on the PR and I will push that up.

**Comment by 0916dhkim** [comment]
@one2code Let's add it as a separate PR. I'll merge this PR first :+1:

**Comment by 0916dhkim** [comment]
Here's an issue for adding --respawn --transpile-only
- https://github.com/EOT-Event-Organizer-s-Toolbox/eot-codebase/issues/99

**Pull request merged**
