### PR TITLE
Connect frontend

### PR DESCRIPTION
**Pull request by igMike-V**
In the middle of connecting the front end, I am having an issue with what the data should look like.  the response from the server is generic and  I am trying to figure out what is not validating.. I think its the date field or the missing id field.  

I don't think we need to send the id with the body since the id will be included in `req.params.id`  but if anyone has an idea what is going wrong please comment.

here is my request body:
{
    "announcementPosted": false,
    "date": "2023-08-10T15:24:11.462Z",
    "eventTypeUUID": "2127c887-5da0-48ac-9ced-07699d31cc04",
    "ideaConfirmed": false,
    "inPersonEvent": false,
    "notes": "",
    "onlineEvent": true,
    "organizer": "Frank",
    "signUpFormSent": false,
    "venue": "",
    "venueContactName": "",
    "venueContactPhone": "",
    "volunteerRequestsSent": false,
    "volunteersNeeded": 4
}

Here is the error
```
BadRequestError: VALIDATION ERROR
    at validationParser (/home/mike/eot-codebase/server/src/utils/validation.ts:20:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at update (/home/mike/eot-codebase/server/src/modules/community-event/controller.ts:31:11) {
  status: 400,
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ]
}
BadRequestError: VALIDATION ERROR```

### CODE REVIEW

**Comment by igMike-V** [comment]
Oops.

I should mention that I created the route for EventTypes in the backend.  I need to get more familiar with how we are building Types from Prisma, but I think I am ~90% there. (We need to call on that API to get the dropdown form on the edit community-event page.)

**Comment by igMike-V** [comment]
Update:   In postman the error was that it was expecting {id, body}

**Comment by anjolaoluwaakindipe** [comment]
> Update: In postman the error was that it was expecting {id, body}

My bad, I thought the id would be included in the request body instead of the request params. I will make sure to change that by today and send a pull request. On the Event types, do you need more information on how to create the endpoint?

**Comment by igMike-V** [comment]
Thanks @anjolaoluwaakindipe.  I think i've got most of the EventType figured out.  I tested POST and GET so far and its woking but I did notice it wasn't returning the description field. ( I didn't check the database yet to see if it saved)

**Pull request merged**
