### PR TITLE
Added services to delete an event by id

### LINKED ISSUE #42: Add service to delete an event
Add and export a function in eventService.tsx: (see examples)

deleteEventById(id): This function will delete a single event by its ID.

### PR DESCRIPTION
**Pull request by anjolaoluwaakindipe**
Resolves #42
Created a function to delete an event by id. I wasn't sure on what should be returned so I made it a asynchronous void function.

### CODE REVIEW

**Review by igMike-V — APPROVED** [review]
In Prisma is this a real delete or does it get flagged for deletion?

**Comment by anjolaoluwaakindipe** [comment]
> In Prisma is this a real delete or does it get flagged for deletion?

We haven't yet implemented a delete endpoint but I think prisma performs an actual delete. We can implement soft delete if we don't want to actaully delete an event from the database

**Review by igMike-V — APPROVED** [review]
Should add deleteEvent to the exports.  then good to merge!

**Comment by igMike-V** [comment]
> We haven't yet implemented a delete endpoint but I think Prisma performs an actual delete. We can implement soft delete if we don't want to actually delete an event from the database

Cool.  Might be something to look into in a future release.

**Comment by anjolaoluwaakindipe** [comment]
> > We haven't yet implemented a delete endpoint but I think Prisma performs an actual delete. We can implement soft delete if we don't want to actually delete an event from the database
> 
> Cool. Might be something to look into in a future release.

Sorry this took time, I got a little busy with school

**Pull request merged**
